#!/bin/bash
#Script used to recursively add and push all files to github account
#Author: Sebastien Luong 

/bin/gitLogin 
echo "Do you want to push following directory \" $(pwd) \" on github? (y/n)"
read CHOICE
if [ "${CHOICE}" = "y" ]; then 
	git add .
	git commit -a 
	git push origin master 
fi 
